# fly.toml file generated for buildecom on 2022-12-07T22:54:21+07:00

app = "buildecom"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "hasrule/restore:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  StripeSettings__PublishableKey="pk_test_51M7hj8BItdeV1CBcgDOkhHpBQUKgGd9pzEA6a2Oom38cJ5BcQwQfICJ3ydB6m8M3GWQX4bVXJbSg5CDtqQ1YDDVY009bEI98hv"
  
[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
